# ~/.config/yazi/yazi.toml

[manager]

show_hidden     =   false
ratio           =   [1, 2, 3]
sort_by         =   "extension"
sort_dir_first  =   true
linemode        =   "permissions"


[opener]
# Editor de texto con Neovim
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" }
]

# Visualizador de imágenes con Eye of GNOME
img = [
  { run = 'eog "$@"', orphan = true, for = "unix" }
]

# Reproductor multimedia con MPV
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" }
]

# PDFs con zathura
pdf = [
  { run = 'zathura "$@"', orphan = true, for = "unix" }
]

# Abrir por defecto (fallback)
default = [
  { run = 'xdg-open "$@"', orphan = true, desc = "Abrir por defecto" }
]

[open]

rules = [
  # Archivos de texto
  { mime = "text/*", use = "edit" },
  { mime = "*.md", use = "edit" },
  { mime = "*.txt", use = "edit" },

  # Imágenes
  { mime = "image/*", use = "img" },
  { mime = "*.png", use = "img" },
  { mime = "*.jpg", use = "img" },
  { mime = "*.jpeg", use = "img" },
  { mime = "*.webp", use = "img" },

  # Video/audio
  { mime = "video/*", use = "play" },
  { mime = "audio/*", use = "play" },
  { mime = "*.mp4", use = "play" },
  { mime = "*.mkv", use = "play" },
  { mime = "*.mp3", use = "play" },
  { mime = "*.flac", use = "play" },
  
  # Archivos PDF
  { mime = "application/pdf", use = "pdf" },
  { mime = "*.pdf", use = "pdf" },

  # Cualquier otro archivo
  { mime = "*", use = "default" }
]


